package io.github.thekekt.mpfr.shim

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Emits the code-generation artifacts for the JNI shim:
 *
 *  - `library/native/jni/mpfr_kmp_ops.h` — X-macro operation tables consumed by
 *    the hand-written `mpfr_kmp_jni.c` dispatch macros (every `mpfr_*` call and
 *    its citation appear exactly once, here);
 *  - `library/src/commonMain/…/internal/MpfrOps.kt` — the matching Kotlin opcode
 *    constants.
 *
 * IDs are emitted in list order (index == id); [ShimTables] must therefore keep
 * the dense 0..n-1 sequences (asserted below — drift fails the build, not the
 * runtime).
 */
object ShimGen {

    private fun assertDense(family: String, entries: List<OpEntry>) {
        entries.forEachIndexed { i, e -> require(e.id == i) { "$family: op ${e.name} id ${e.id} != index $i" } }
    }

    private fun xmacro(name: String, entries: List<OpEntry>, withCite: Boolean): String =
        buildString {
            appendLine("/* $name — each row: OP(NAME, id, mpfr-call-expression)")
            for (e in entries) appendLine("  KMP_OP(${e.name}, ${e.id}, ${e.c})")
            append("/* citations: */\n")
            for (e in entries) appendLine("  KMP_CITE(${e.name} /* ${e.cite} */)")
        }

    fun opsHeader(): String {
        assertDense("binary", ShimTables.binary)
        assertDense("fused", ShimTables.fused)
        assertDense("unary", ShimTables.unary)
        assertDense("scalar", ShimTables.scalar)
        assertDense("double", ShimTables.doubleOps)
        assertDense("pair", ShimTables.pair)
        assertDense("const", ShimTables.consts)
        assertDense("predicates", ShimTables.predicates)
        return buildString {
            appendLine("/* GENERATED by :library:generateShim from buildSrc/.../ShimTables.kt — do not edit.")
            appendLine(" *")
            appendLine(" * MPFR op dispatch tables for the JNI shim. The hand-written mpfr_kmp_jni.c")
            appendLine(" * defines one consumer macro KMP_BIN_OP(name,id,call) (etc.) and #includes this")
            appendLine(" * file; every generated expression uses ONLY the variables bound by the enclosing")
            appendLine(" * switch family scope:")
            appendLine(" *   binary:   rop, x, y, r          fused: rop, x, y, z, r")
            appendLine(" *   unary:    rop, x, r   (rop pre-copied from x)")
            appendLine(" *   scalar:   rop, x, tmp, k (intmax), r — tmp is MPFR-prec ${ShimTables.TMP_PREC_INT}, exact via set_sj")
            appendLine(" *   double:   rop, x, tmp, d, r — tmp prec ${ShimTables.TMP_PREC_DBL}, set_d exact")
            appendLine(" *   pair:     rop, rop2, x, r       const: rop, tmp, r")
            appendLine(" *   predicate: x, y — result: jint 0/1")
            appendLine(" */")
            appendLine("#ifndef MPFR_KMP_OPS_H")
            appendLine("#define MPFR_KMP_OPS_H")
            appendLine()
            appendLine("/* --- family expansions: (name, id, mpfr call) triples --------------------------- */")
            appendLine("#define KMP_BINARY_OPS(K) \\")
            appendJoined(ShimTables.binary, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_FUSED_OPS(K) \\")
            appendJoined(ShimTables.fused, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_UNARY_OPS(K) \\")
            appendJoined(ShimTables.unary, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_SCALAR_OPS(K) \\")
            appendJoined(ShimTables.scalar, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_DOUBLE_OPS(K) \\")
            appendJoined(ShimTables.doubleOps, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_PAIR_OPS(K) \\")
            appendJoined(ShimTables.pair, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_CONST_OPS(K) \\")
            appendJoined(ShimTables.consts, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine("#define KMP_PREDICATE_OPS(K) \\")
            appendJoined(ShimTables.predicates, "K") { e -> "    K(${e.name}, ${e.id}, ${e.c})" }
            appendLine()
            appendLine("/* --- format style letters (index == id) ----------------------------------------- */")
            appendLine("/* SCIENTIFIC/ FIXED / GENERAL — mpfr_snprintf %R<letter>; digits=0 keeps MPFR default */")
            appendLine("#define KMP_FORMAT_LETTERS X('e') X('f') X('g')")
            appendLine()
            appendLine("/* --- citations, one entry per op (documentation only) --------------------------- */")
            appendLine("#define KMP_BINARY_CITES(X) \\")
            appendJoined(ShimTables.binary, "X") { e -> "    X(${e.name} ${e.id} /* ${e.cite} */)" }
            appendLine("#define KMP_UNARY_CITES(X) \\")
            appendJoined(ShimTables.unary, "X") { e -> "    X(${e.name} ${e.id} /* ${e.cite} */)" }
            appendLine()
            append("#endif /* MPFR_KMP_OPS_H */\n")
        }
    }

    private fun <T> StringBuilder.appendJoined(entries: List<T>, macro: String, line: (T) -> String): StringBuilder {
        entries.forEachIndexed { i, e ->
            appendLine(line(e) + if (i == entries.size - 1) "" else " \\")
        }
        return this
    }

    fun kotlinSource(): String {
        assertDense("binary", ShimTables.binary)
        return buildString {
            appendLine("package io.github.thekekt.mpfr.internal")
            appendLine()
            appendLine("import io.github.thekekt.mpfr.InternalMpfrApi")
            appendLine()
            appendLine("/* GENERATED by gradlew :library:generateShim from buildSrc .../ShimTables.kt —")
            appendLine(" * do not edit by hand (the same table drives native/jni/mpfr_kmp_ops.h and,")
            appendLine(" * through it, the switch bodies in mpfr_kmp_jni.c). Dispatch opcode ids. */")
            appendLine()
            appendOps("MpfrBinaryOp", ShimTables.binary)
            appendOps("MpfrFusedOp", ShimTables.fused)
            appendOps("MpfrUnaryOp", ShimTables.unary)
            appendOps("MpfrScalarOp", ShimTables.scalar)
            appendOps("MpfrDoubleOp", ShimTables.doubleOps)
            appendOps("MpfrPairOp", ShimTables.pair)
            appendOps("MpfrConstOp", ShimTables.consts)
            appendOps("MpfrPredicateOp", ShimTables.predicates)
            appendOps("MpfrFormatStyle", ShimTables.formatStyles)
        }
    }

    private fun StringBuilder.appendOps(objectName: String, entries: List<OpEntry>) {
        appendLine("@InternalMpfrApi")
        appendLine("internal object $objectName {")
        for (e in entries) appendLine("    const val ${e.name}: Int = ${e.id} // ${e.cite} — ${e.c}")
        appendLine("}")
        appendLine()
    }
}

abstract class GenerateShimTask : DefaultTask() {
    @get:OutputFile abstract val opsHeaderFile: RegularFileProperty

    @get:OutputFile abstract val kotlinOpsFile: RegularFileProperty

    @TaskAction
    fun generate() {
        opsHeaderFile.get().asFile.apply { parentFile.mkdirs(); writeText(ShimGen.opsHeader()) }
        kotlinOpsFile.get().asFile.apply { parentFile.mkdirs(); writeText(ShimGen.kotlinSource()) }
    }
}
